### ISSUE TITLE
coverage unknown readme badge

### ISSUE THREAD

**Issue by matkoniecz** [simplexspatial/osm4scala#46]
https://github.com/simplexspatial/osm4scala#osm4scala 

It should be either fixed or removed, there is no point in the current one

**Comment by angelcervera** [comment]
Thanks, @matkoniecz Good catch!

The problem is related to Travis-CI. The configuration is using the old travis-ci.org account for OSS. Looks like now it is necessary to move to Travis-CI.com, even if it is OSS.

Documentation:
- [Announcement](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom)
- [Migration guide](https://docs.travis-ci.com/user/migrate/open-source-repository-migration)

**Comment by angelcervera** [comment]
Coverage is 96% but still 86% in the budge. Weird.
